# Generated by Django 4.0.4 on 2022-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Vendor', 'Vendor')], default='Buyer', help_text='Sallers has their own shops / Buyers can buy products.', max_length=256),
        ),
    ]
