# Generated by Django 4.0.4 on 2022-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Saller', 'Saller')], default='Buyer', help_text='Sallers has their own shops / Buyers can buy products.', max_length=256),
        ),
    ]
