# Generated by Django 3.2.9 on 2022-04-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_question_quiztitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quiztitle',
            name='total_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiztitle',
            name='total_marks',
            field=models.IntegerField(null=True),
        ),
    ]
