# Generated by Django 3.2.9 on 2022-04-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_auto_20220425_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizheader', to='app_auth.quiztitle'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_answered', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('questions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_auth.question')),
                ('quiztitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizname', to='app_auth.quiztitle')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
