# Generated by Django 4.0.4 on 2022-05-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_alter_coupon_vendor'),
        ('app_order', '0002_alter_cart_id_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_shop.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='applycoupon',
            field=models.BooleanField(default=False),
        ),
    ]
