# Generated by Django 4.0.4 on 2022-05-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0003_order_coupon_order_applycoupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Coupon',
            new_name='coupon',
        ),
    ]
