# Generated by Django 4.0.4 on 2022-05-21 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shop', '0003_product_product_saller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_saller',
            new_name='product_Saller',
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='Coupon Code')),
                ('short_desc', models.TextField(max_length=500, null=True, verbose_name='Short Description')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
